#!/usr/bin/env node
"use strict";

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const sha = execSync("git rev-parse HEAD").toString().trim();
const shortSha = sha.slice(0, 7);

const content = `// Auto-generated by scripts/generate-version.js — do not edit manually.
export const VERSION = "${shortSha}";
`;

const outPath = path.join(__dirname, "..", "src", "version.ts");
fs.writeFileSync(outPath, content, "utf8");
console.log(`Generated src/version.ts with VERSION="${shortSha}"`);
